config/routes.rb
Rails.application.routes.draw do
	resources :payment_types
	resources :project_categories
	
	resources :projects do
	  resources :gifts
	end

	resources :user_projects
	resources :users
	resources :sessions

	root 'projects#index'
	get 'signup', to: 'users#new', as: 'signup'
  	get 'login', to: 'sessions#new', as: 'login'
  	get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
	has_many :gifts
	belongs_to :project
end

app/models/gift.rb
class Gift < ApplicationRecord
	belongs_to :project
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
	belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :contributions
	has_many :gifts
	has_many :project_project_types
	has_many :project_categories, through: :project_project_types


	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/project_category.rb
class ProjectCategory < ApplicationRecord
	has_many :project_project_types
	has_many :projects, through: :project_project_types


end

app/models/project_project_type.rb
class ProjectProjectType < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
	has_many :payment_types
	has_many :gifts
	has_many :projects

	has_secure_password
 
    validates_uniqueness_of :email
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
	def index
		@gifts = Gift.all
	end

	def new
		@project = Project.find(params[:project_id])
		@gift = Gift.new
	end

	def show
		@gift = Gift.find(params[:id])
	end


	def create
		@project = Project.find(params[:project_id])
		@gift = @project.gifts.create(gift_params)

		if @gift.save
			redirect_to projects_path
		else
			render 'new'
		end
		
	end


	private

		def gift_params
			params.require(:gift).permit(:title, :description, :minimum_donation)
		end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = if params[:term]
		Project.where('title LIKE ?', "%#{params[:term]}%")
		else
		@projects = Project.all
		end
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		@project.user_id = session[:user_id]
		puts "HERE #{@project.inspect}"
		if @project.save
			redirect_to @project
		else
			render 'new'
		end
		
	end

	def show
	    @project = Project.find(params[:id])
	end



	private

		def project_params

			params.require(:project).permit(:title, :description, :funding_goal, :start_date, :end_date, :user_id, :image, :project_type_id, :term)

		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
   def index
     @users = User.where(:id => session[:user_id])
     @payment_types = PaymentType.where(:user_id => session[:user_id])
   end


   def new
     @user = User.new
   end
 
   def create
     @user = User.new(user_params)
     if @user.save
       session[:user_id] = @user.id
       redirect_to root_url, notice: 'Thank you for signing up!'
     else
       render :new
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :street_address, :city, :state, :postal_code, :phone_number)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   def index
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
   private
 
   def logged_in?
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/project_categories_helper.rb
module ProjectCategoriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gifts/new.html.erb
<h1>Add Gift to Project</h1>

<div class="container">
		<div class="form-group">
			<%= form_with(model: [@project, @project.gifts.build], local: true) do |f| %>

				<% if @gift.errors.any? %>
				    <div id="error_explanation">
				      <h2>
				        <%= pluralize(@gift.errors.count, "error") %> prohibited
				        this gift from being saved:
				      </h2>
				      <ul>
				        <% @gift.errors.full_messages.each do |msg| %>
				          <li>
				          	 <div class="alert alert-danger"><%= msg %></div>
				          </li>
				        <% end %>
				      </ul>
				    </div>
				<% end %>

				<p>
					<%= f.label :title %><br>
					<%= f.text_field(:title, {:class => 'form-control'}) %>
				</p>

				<p>
					<%= f.label :description %><br>
					<%= f.text_area(:description, {:class => 'form-control'}) %>
				</p>

				<p>
					<%= f.label :minimum_donation %><br>
					<%= f.text_field(:minimum_donation, {:class => 'form-control'}) %>
				</p>

				<p>
					<%= f.submit "Add Gift" %>
				</p>

			<% end %>

		</div>
</div>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<div class="row">
	<% @projects.each do |project| %>
		<div class="col-md-4">
			<h1><%= link_to project.title, project_path(project) %></h1>
			<h3><%= project.description %></h3>
			<h3>Funding Goal: <%= number_to_currency(project.funding_goal) %></h3>
			Start Date: <%= project.start_date %> <br>
			End Date: <%= project.end_date %>
			
			<% now = Date.today %>
			<% if project.start_date < now %>
				<% if project.end_date > now %>
					<h6 class="active-project">This project is active now!</h6>
					<h4><%= link_to "Contribute", project_path(project), class: "btn btn-primary" %></h4>
				<% else %>
					<h6 class="past-project">This project ended on <%= project.end_date %>. </h6>
					<h4><%= link_to "Contribute", project_path(project), class: "btn btn-primary disabled" %></h6>
				<% end %>
			<% else %>
					<h6 class="future-project">This project will be active on <%= project.start_date %>. </h6>
					<h4><%= link_to "Contribute", project_path(project), class: "btn btn-primary disabled" %></h4>
			<% end %>
	
		</div>
	<% end %>
</div>

app/views/projects/new.html.erb
<h1>New Crowdfund Project</h1>

<div class="container">
		<div class="form-group">
			<%= form_for @project, html: { multipart: true } do |f| %>

				<% if @project.errors.any? %>
				    <div id="error_explanation">
				      <h2>
				        <%= pluralize(@project.errors.count, "error") %> prohibited
				        this project from being saved:
				      </h2>
				      <ul>
				        <% @project.errors.full_messages.each do |msg| %>
				          <li>
				          	 <div class="alert alert-danger"><%= msg %></div>
				          </li>
				        <% end %>
				      </ul>
				    </div>
				<% end %>

				<p>
					<%= f.label :title %><br>
					<%= f.text_field(:title, {:class => 'form-control'}) %>
				</p>

				<p>
					<%= f.label :description %><br>
					<%= f.text_area(:description, {:class => 'form-control'}) %>
				</p>
				
				<p>
					<%= f.label :project_type_id, "Project Type" %>

						<% @project_types = ProjectCategory.all %>
						<%= f.collection_select :project_type_id, @project_types, :id, :project_type, include_blank:true%>
				
				</p>

				<p>
					<%= f.label :funding_goal %><br>
					<%= f.text_field(:funding_goal, {:class => 'form-control'}) %>
				</p>

				<p>
					<%= f.label :start_date %><br>
					<%= f.date_field(:start_date, {:class => 'form-control'})%>
				</p>

				<p>
					<%= f.label :end_date %><br>
					<%= f.date_field(:end_date, {:class => 'form-control'})%>
				</p>

				<p>
					<%= f.label :image %>
					<%= f.file_field(:image, {:class => 'form-control'}) %>
				</p>

				<p>
					<%= f.submit "Start Crowdfunding" %>
				</p>

			<% end %>

		</div>
</div>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<h3><%= @project.description %></h3>
<h3>Funding Goal: <%= number_to_currency(@project.funding_goal) %></h3>
Start Date: <%= @project.start_date %> <br>
End Date: <%= @project.end_date %><br>

<h3>Gifts for supporting this project:</h3>

<% @gifts = Gift.where("project_id == #{@project.id}") %>
<% @gifts.each do |gift| %>

	<h5><%= gift.title %></h5>
	<h5>Description: <%= gift.description %></h5>
	<h5>Minimum Donation: <%= number_to_currency(gift.minimum_donation) %></h5>
	<br>

<% end %>

<br>
<br>
<br>

<p><%= link_to "Add gifts for those that donate.", new_project_gift_path(@project), class: "btn btn-primary" %></p>

app/views/users/index.html.erb
<h1>Account Details</h1>

<% @users.each do |user| %>
	<h3> <%= user.first_name %> <%= user.last_name %> </h3>
	<h3> <%= user.email %> </h3>
	<h3> <%= user.street_address %> </h3>
	<h3> <%= user.city %>, <%= user.state %> <%= user.postal_code %> </h3>
<% end %>

<h3>Payment Types</h3>
<h4><%= link_to "Add Payment Type", new_payment_type_path, class: "btn btn-primary" %></h4>

<% @payment_types.each do |payment| %>
	<h4> <%= payment.title %> </h4>
	<h4> <%= payment.account_number %></h4>
	<div><%= link_to 'Edit', edit_payment_type_path(payment) %></div>
	<div><%= link_to 'Destroy', payment,
              :method =>'delete',
              :data => { confirm: 'Are you sure?' } %></div>
<% end %>

<h3>Your Created Projects</h3>
<% @user_projects = Project.where(:user_id => session[:user_id]).order(:created_at)%>
<% now = Date.today %>
<% @user_projects.each do |project| %>
	<div><%= link_to project.title, project %> | <%= project.created_at.strftime("Created on %m/%d/%Y") %> |
		<% if project.start_date > now %>
			<%= link_to 'Edit', edit_project_path(project) %> |
			<%= link_to 'Delete', project,
				:method => 'delete',
				:data => { confirm: 'Are you sure?' } %>
		<% elsif project.start_date < now and project.end_date > now %>
			<%= link_to 'Edit', edit_project_path(project) %>
		<% end %>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br />
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>