config/routes.rb
Rails.application.routes.draw do
	resources :payment_types
	resources :project_categories
	
	resources :projects do
	  resources :gifts
	end

	resources :user_projects
	resources :users
	resources :sessions

	root 'projects#index'
	get 'signup', to: 'users#new', as: 'signup'
  	get 'login', to: 'sessions#new', as: 'login'
  	get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
	has_many :gifts
	belongs_to :project
end

app/models/gift.rb
class Gift < ApplicationRecord
	belongs_to :project
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
	belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :contributions
	has_many :gifts
	has_many :project_project_types
	has_many :project_categories, through: :project_project_types


	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/project_category.rb
class ProjectCategory < ApplicationRecord
	has_many :project_project_types
	has_many :projects, through: :project_project_types


end

app/models/project_project_type.rb
class ProjectProjectType < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
	has_many :payment_types
	has_many :gifts
	has_many :projects

	has_secure_password
 
    validates_uniqueness_of :email
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
	def index
		@gifts = Gift.all
	end

	def new
		@project = Project.find(params[:project_id])
		@gift = Gift.new
	end

	def show
		@gift = Gift.find(params[:id])
	end


	def create
		@project = Project.find(params[:project_id])
		@gift = @project.gifts.create(gift_params)

		if @gift.save
			redirect_to projects_path
		else
			render 'new'
		end
		
	end


	private

		def gift_params
			params.require(:gift).permit(:title, :description, :minimum_donation)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
   def index
     @users = User.where(:id => session[:user_id])
     @payment_types = PaymentType.where(:user_id => session[:user_id])
   end


   def new
     @user = User.new
   end
 
   def create
     @user = User.new(user_params)
     if @user.save
       session[:user_id] = @user.id
       redirect_to root_url, notice: 'Thank you for signing up!'
     else
       render :new
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :street_address, :city, :state, :postal_code, :phone_number)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   def index
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
   private
 
   def logged_in?
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfundingapp</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css' %>

  </head>

  <body>
    <% if logged_in? %>
             	<nav class="navbar navbar-expand-lg navbar-light bg-light">
                  <%= link_to "Crowdfunder", projects_path, class: "navbar-brand" %>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item"><%= link_to "Home", projects_path, class: "nav-link" %></li>
                    </ul>

                  </div>
                  <div class="collapse navbar-collapse" id="navbarNav">
           
                  <%= form_tag(projects_path, :method => :get) do %>
                    <%= text_field_tag :term, nil, 
                    {:placeholder => "Search All Projects"} %>
                  <% end %>
              
                      <ul class="navbar-nav ml-auto">
                          <li class="nav-item align-self-end"><%= link_to "My Account", users_path, class: "nav-link" %></li>
                          <li class="nav-item align-self-end"><%= link_to "Log Out", logout_path, class: "nav-link" %></li>
                      </ul>
                  </div>
                </nav>

      <% else %>
                <%= link_to 'Login', login_path, class: "" %>
                <%= link_to 'Sign Up', signup_path %>

      <% end %>


    <div class="container">

            <%= yield %>
    </div>


  </body>
</html>